name: android_client
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
    sdk: '>=3.2.4 <4.0.0'

dependencies:
    flutter:
        sdk: flutter
    carousel_slider: ^4.0.0
    http: ^1.2.0
    socket_io_client: ^2.0.0
    shared_preferences: ^2.2.2
    email_validator: ^2.1.17
    crypto: ^3.0.3
    encrypt: ^5.0.3
    fullscreen_window: ^1.0.3
    flutter_rx: ^0.5.1
    provider: ^5.0.0
    camera: ^0.10.5+9
    path_provider: ^2.1.2
    path: ^1.8.3
    permission_handler: ^11.3.0
    rxdart: ^0.27.7
    audioplayers: ^5.2.1
    get: ^4.6.6
    flutter_rating_bar: ^4.0.0
    flutter_colorpicker: ^1.0.3
    firebase_core: ^2.27.0
    firebase_messaging: ^14.7.19
    flutter_local_notifications: ^17.0.0
    video_player: ^2.2.11

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^2.0.0
    test: ^1.24.9
    flutter_launcher_icons: ^0.13.1

flutter_ions:
    image_path: 'assets/images/logo.png'
    android: true

flutter:
    uses-material-design: true
    assets:
        - assets/images/logo.png
        - assets/audio/message.wav
        - assets/audio/friend.wav
        - assets/audio/valid_sound.mp3
        - assets/audio/invalid_sound.mp3
