// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeMvqI5qlOON9okbQxVhX9fYIr5XvxMX8',
    appId: '1:1097315199531:web:90f8ead1d6e19645d4d86e',
    messagingSenderId: '1097315199531',
    projectId: 'log3900app',
    authDomain: 'log3900app.firebaseapp.com',
    storageBucket: 'log3900app.appspot.com',
    measurementId: 'G-YRQYFTMN39',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD30bdH4lGqH-w6JbyQsoHHyFDCBG6pbhg',
    appId: '1:1097315199531:android:baf44897a28b5a1bd4d86e',
    messagingSenderId: '1097315199531',
    projectId: 'log3900app',
    storageBucket: 'log3900app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWiGiWChnoAX54HaMtFQgUEQhKCjkeOdc',
    appId: '1:1097315199531:ios:c9de76a7d9c6cabdd4d86e',
    messagingSenderId: '1097315199531',
    projectId: 'log3900app',
    storageBucket: 'log3900app.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWiGiWChnoAX54HaMtFQgUEQhKCjkeOdc',
    appId: '1:1097315199531:ios:5d4a28b364978125d4d86e',
    messagingSenderId: '1097315199531',
    projectId: 'log3900app',
    storageBucket: 'log3900app.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
